FAILED_VALIDATION = "Parameter validation failed"
PITR_ENABALED = "Point-In-Time-Recovery enabled successfully"
TABLE_EXPORTED = "Table successfully exported to s3"
MESSAGE_PUSHED = "Message pushed successfully in SQS queue"
NONE_VALUE = "Something went wrong! Please check the credential you entered"
PITR_ALREADY_ENABALED = "Point-in-time-recovery is already enabled"